---

# Plugin messages (Feel free to edit if you are in a different language)
#
# '{NAME}' is the name of the form (e.g. would return 'ExampleForm')
# '{KEY}' is the command key (e.g. would return '1')
messages:
  errors:
    invalid-sender: 'Error: This command can only be executed by players'
    no-forms: 'No valid form data section was found, disabling plugin.'
    no-messages: 'No messages where, rewriting default messages.'
    invalid_form: 'No form data has showed up for the form {NAME}.'
  warnings:
    form:
      title: 'The form {NAME} has no valid title set.'
      command: 'The form {NAME} has no valid command field set.'
      command-label: 'The form {NAME} has no valid command label set.'
      type: 'The form {NAME} has no valid type set.'
    commands:
      sender: 'The command {KEY} in the form {NAME} has no valid sender set.'
      label: 'The command {KEY} in the form {NAME} has no valid label set.'
      invalid-sender: 'The command {KEY} in the form {NAME} has an invalid sender.'



# Forms data area (This is where your forms will be)
forms:

  # Form internal identifier (This can be anything, keep in mind that there can be)
  example:

    # Form type (Currently implemented: simple, modal)
    type: "simple"

    # Command data (label is required, nothing else is)
    command:
      label: "opensimpleform"
      description: "Opens the example ui"
      permission: "formcreator.simpleeg.use"

    # Form data (title is required, content is not)
    title: "&aSimple Form Example"
    content: "&aHello {PLAYER}! :) {LINE} &bOnline players&7: &l&3{ONLINE_PLAYERS}&8/&3{MAX_PLAYERS} {LINE}{LINE} This plugin is cool :)"

    # Buttons
    buttons:

      # Add your buttons here
      # The index will be the button's display name
      "&eButton 1{LINE}&eClick me!!":

        # Image data (Delete these to disable an image)
        image-type: 0
        image-path: "textures/ui/MashupIcon"

        # Here are the commands that the button will execute
        # You can set the sender for each command (Both label and sender are required)
        commands:
          - label: "title {PLAYER} title Welcome!"
            sender: "console"
          - label: "say &bHello {PLAYER}!"
            sender: "player"


      "&cButton 2":
        commands:
          - label: "title {PLAYER} title Awesome!"
            sender: "console"

          - label: "say &bThis plugin is cool!"
            sender: "player"

  modal-example:

    type: "modal"

    title: "&aModal Form Example"
    content: "&aHello {PLAYER}! :) {LINE} &bOnline players&7: &l&3{ONLINE_PLAYERS}&8/&3{MAX_PLAYERS} {LINE}{LINE} This plugin is cool :)"

    button1:
      label: "&aYes"
      commands :
        - label: "title {PLAYER} title Welcome!"
          sender: "console"
        - label: "say &bHello {PLAYER}!"
          sender: "player"

    # Button two is also triggered when the modal form is exited 
    button2:
      label: "&cNo"
      commands:
        - label: "title {PLAYER} title Awesome!"
          sender: "console"

        - label: "say &bThis plugin is cool!"
          sender: "player"


    command:
      label: "openmodalform"
      description: "Opens the example modal form"
      permission: "formcreator.modaleg.use"
